<script type="text/x-magento-init">
    {
        "#target": {
            "coffee": {
                "base_url": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
            }
        }
    }
</script>
<div id="target"></div>

<p>444 111 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium corporis, eligendi fugit impedit laborum molestias quaerat similique vitae? Aliquam dignissimos omnis praesentium quis sunt voluptatibus. Aperiam assumenda at blanditiis consectetur distinctio dolorem ea eius, eligendi expedita illum impedit ipsum laborum maiores nulla perferendis porro possimus provident quasi sapiente tempore veniam voluptate voluptatem. Aliquam beatae dolore est exercitationem expedita facere fugit, incidunt laborum laudantium minima molestiae obcaecati omnis perferendis possimus quaerat reiciendis sed vel. Ab aliquid consequatur dicta eius explicabo molestias, necessitatibus quae quam, quisquam reprehenderit sint ut voluptate. Culpa ducimus earum expedita explicabo fuga iure nemo nobis odit quaerat voluptate.</p>
