<h2>WIDGETS:</h2>

<div id="test-collapsible" data-mage-init='{"Magento_Cms/js/widgets/dynamic-collapsible": {
                                            "active": true,
                                            "saveState": true,
                                            "ajaxContent": true,
                                            "animate": {
                                                "duration": 600,
                                                "easing": "linear"
                                            }}}'>
    <div data-role='title'>
        <h2>How about collapsible widget??? <button data-role="trigger">GO</button></h2>
    </div>
    <div id="example" data-role='content'></div>
    <a href="<?= $block->getViewFileUrl('Magento_Cms/template/widget/collapsible-example-content.html') ?>" data-ajax="true"></a>
</div>
